---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/backend" # Location of package manifests
    schedule:
      interval: "daily"
      
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/frontend" # Location of package manifests
    schedule:
      interval: "daily"

  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/healthcheck" # Location of package manifests
    schedule:
      interval: "daily"
