---
include:
  - path: docker-compose.backend.yml
  - path: docker-compose.db.yml
  - path: docker-compose.frontend.yml

volumes:
  backendlog:
  redis:
  redis-config:
  sec-redis:
  sec-redis-config:
  
networks:
  api-network:
    driver: bridge
  app-network:
    driver: bridge
  db-network:
    driver: bridge
  security-network:
    driver: bridge
