---
services:
  proxy:
    build: 
      context: ./proxy
      dockerfile: Dockerfile
    image: proxy
    container_name: proxy
    restart: always
    ports:
      - 8080:8080
      - 9901:9901
    depends_on:
      - backend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    container_name: frontend
    restart: always
    environment:
      - GrpcEndpointUrl=localhost:8080
    ports:
      - 3000:3000
    depends_on:
      - backend
      - proxy