---
include:
  - path: docker-compose.backend.yml
  - path: docker-compose.db.yml
  - path: docker-compose.frontend.yml

volumes:
  backendlog:
  redis:
  redis-config:
  sec-redis:
  sec-redis-config:
