---
services:
  proxy:
    build: ./proxy
    image: proxy
    container_name: proxy
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network
      - api-network
  frontend:
    build: ./frontend
    image: frontend
    container_name: frontend
    restart: always
    environment:
      - GrpcEndpointUrl=localhost:8080
    ports:
      - 3000:3000
    depends_on:
      - backend
      - proxy
    networks:
      - app-network